@startuml
title Definition und Erfassung zusätzlicher Eigenschaften

skinparam shadowing false
skinparam roundcorner 0
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam classAttributeFontName Monospaced

skinparam ArrowColor #555555
skinparam classBorderColor #555555

hide circle


class "AdditionalPropertiesQuestionnaire" as Questionnaire #D9EAD3 {
  item                  BackboneElement   0..*
}

class "Questionnaire.item" as Question #D9EAD3 {
  linkId                String            1..1
  type                  Code              1..1
  --
  text                  String            0..1
}

class "AdditionalPropertiesQuestionnaireResponse" as Response #FFF2CC {
  questionnaire         Canonical         1..1
  item                  BackboneElement   1..*
}

class "QuestionnaireResponse.item" as Answer #FFF2CC {
  linkId                String            1..1
  answer                BackboneElement   0..*
}

Questionnaire "1" *-- "0..*" Question : item

Response "0..*" --> "1" Questionnaire : questionnaire

Response "1" *-- "1..*" Answer : item

Question ..> Answer : linkId

@enduml