@startuml
title Create Person 

class AffectedPerson{
}
class EmigaUserPractitioner {
}
class TransactionBundle {
    <b>+</b> type: FixedValue ('transaction') [1..1]
}

AffectedPerson --> AffectedPersonRelatedPerson : link.relatedPersonLink
AffectedPerson --> EmigaUserPractitioner : lastModifiedBy

TransactionBundle ..> AffectedPerson : entry[0]
TransactionBundle ..> EmigaUserPractitioner : entry[1]
TransactionBundle ..> AffectedPersonRelatedPerson : entry[2]


@enduml