@startuml
skinparam linetype ortho

title Create Annotation - Class Diagram

class Bundle{
    <b>+</b> type: FixedValue ('transaction') [1..1]
}
class AnnotationCommunication{
}
class AttachmentDocumentReference {
}
class EmigaUserPractitioner {
}

AnnotationCommunication --> EmigaUserPractitioner : author
AnnotationCommunication --> AttachmentDocumentReference : payload

Bundle ..> AnnotationCommunication : entry[0]
Bundle ..> EmigaUserPractitioner : entry[1]
Bundle ..> AttachmentDocumentReference : entry[2]

@enduml