/'
@startuml

title RelatedPerson 

class AffectedPerson{
}
class Relationship{
}
class AffectedPersonRelatedPerson {
}
class Patient {
}
class Relationship{
}

AffectedPerson --> AffectedPersonRelatedPerson: Link

AffectedPersonRelatedPerson --> Patient: Bezugsperson
AffectedPersonRelatedPerson --> Relationship: Beziehung zur betroffenen Person

@enduml
'/

@startuml

title RelatedPerson

class AffectedPerson {
}
class AffectedPersonRelatedPerson {
}
class Relationship {
}

AffectedPerson --> AffectedPersonRelatedPerson : Bezugsperson
AffectedPersonRelatedPerson --> Relationship : Beziehung zur betroffenen Person

@enduml