@startuml

title RelatedPerson

skinparam shadowing false
skinparam roundcorner 0
skinparam linetype spline
skinparam classAttributeIconSize 0
skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam classAttributeFontName Monospaced

hide circle

class AffectedPerson{
}
class Relationship{
}
class AffectedPersonRelatedPerson {
}
class Patient {
}
class Relationship{
}

AffectedPerson --> AffectedPersonRelatedPerson: Link

AffectedPersonRelatedPerson --> Patient: Bezugsperson
AffectedPersonRelatedPerson --> Relationship: Beziehung zur betroffenen Person

@enduml