CodeSystem: ResourceResponsibility
Id: ResourceResponsibility
Title: "ResourceResponsibility"
Description: "Die Kodiersystematik 'ResourceResponsibility' definiert Konzepte, die für die Auszeichnung der Verantwortlichkeit für Ressourcen genutzt werden kann."
* insert MetadataTerminology
* ^version = "1.1.0"
* ^date = "2025-05-05"
* ^caseSensitive = true
* ^content = #complete
* ^valueSet = "https://emiga.rki.de/fhir/common/ValueSet/ResourceResponsibility"
* ^count = 404

* #0. "-kein-"
* #1. "Robert Koch-Institut"
* #1.01. "Universitätsklinikum Schleswig Holstein (Campus Kiel / Inst. f. Infektionsmedizin)"
* #1.01.0.01. "Stadt Flensburg (Fachbereich 2 / Gesundheitsdienste)"
* #1.01.0.02. "Landeshauptstadt Kiel (Amt für Gesundheit)"
* #1.01.0.03. "Hansestadt Lübeck (Gesundheitsamt)"
* #1.01.0.04. "Stadt Neumünster (Gesundheitsamt)"
* #1.01.0.51. "Kreis Dithmarschen (Fachdienst Gesundheitsschutz)"
* #1.01.0.53. "Kreis Herzogtum Lauenburg (Gesundheitsamt)"
* #1.01.0.54. "Kreis Nordfriesland (Fachdienst Gesundheit(Gesundheitsamt))"
* #1.01.0.55. "Kreis Ostholstein (Fachdienst Gesundheit(Gesundheitsamt))"
* #1.01.0.56. "Kreisverwaltung Pinneberg (Fachdienst Gesundheit)"
* #1.01.0.57. "Kreis Plön (Amt für Gesundheit)"
* #1.01.0.58. "Kreis Rendsburg-Eckernförde (Fachdienst 4.3 Gesundheitsdienste)"
* #1.01.0.59. "Kreis Schleswig-Flensburg (Fachdienst Gesundheit)"
* #1.01.0.60. "Landkreis Segeberg (Fachbereich Gesundheit für Mensch und Tier)"
* #1.01.0.61. "Landkreis Steinburg (Gesundheitsamt)"
* #1.01.0.62. "Landkreis Stormarn (Fachdienst Gesundheit/ Gesundheitsamt)"
* #1.02. "Zentrum für Infektionsepidemiologie (Institut für Hygiene und Umwelt)"
* #1.02.0.01. "Bezirksamt Hamburg-Altona (Bezirksamt Altona)"
* #1.02.0.02. "Bezirksamt Hamburg-Bergedorf (Fachamt Gesundheit)"
* #1.02.0.03. "Bezirksamt Hamburg-Eimsbüttel (Gesundheits- und Umweltamt)"
* #1.02.0.04. "Bezirksamt Hamburg-Mitte (Gesundheits- und Umweltamt)"
* #1.02.0.05. "Bezirksamt Hamburg-Nord (Fachamt Gesundheit)"
* #1.02.0.06. "Bezirksamt Hamburg-Harburg (Bezirksamt Harburg)"
* #1.02.0.07. "Bezirksamt Hamburg-Wandsbek (Gesundheits- und Umweltamt)"
* #1.02.0.08. "HPHC (Hafenärztlicher Dienst)"
* #1.03. "Niedersächsisches Landesgesundheitsamt (Abt. Infektionsepidemiologie)"
* #1.03.1.01. "Stadt Braunschweig (Fachbereich Soziales und Gesundheit)"
* #1.03.1.02. "Stadt Salzgitter (Gesundheitsamt)"
* #1.03.1.03. "Stadt Wolfsburg (Gesundheitsamt)"
* #1.03.1.51. "Landkreis Gifhorn (Fachbereich Gesundheit)"
* #1.03.1.53. "Landkreis Goslar (Gesundheitsamt)"
* #1.03.1.54. "Landkreis Helmstedt (Geschäftsbereich Gesundheit)"
* #1.03.1.55.03. "Landkreis Northeim (Gesundheitswesen)"
* #1.03.1.57. "Landkreis Peine (Gesundheitsamt)"
* #1.03.1.58. "Landkreis Wolfenbüttel (Gesundheitsamt)"
* #1.03.1.59. "Stadt und Landkreis Göttingen (Fachbereich 53 Gesundheitsamt)"
* #1.03.2.41. "Region Hannover (Fachbereich Gesundheit)"
* #1.03.2.51. "Landkreis Diepholz (Fachdienst 53 Gesundheitsamt)"
* #1.03.2.52. "Landkreis Hameln-Pyrmont (Gesundheitsamt)"
* #1.03.2.54. "Landkreis Hildesheim (FD 409 Fachdienst Gesundheit)"
* #1.03.2.55. "Landkreis Holzminden (Gesundheitsamt)"
* #1.03.2.56. "Landkreis Nienburg (Weser) (FD 414 Sozialmedizin, Hygiene und Umwelt)"
* #1.03.2.57.01. "Landkreis Schaumburg (Gesundheitsamt)"
* #1.03.3.51. "Landkreis Celle (Gesundheitsamt)"
* #1.03.3.52. "Landkreis Cuxhaven (Gesundheitsamt)"
* #1.03.3.53. "Landkreis Harburg (Gesundheitsamt)"
* #1.03.3.54. "Landkreis Lüchow-Dannenberg (Gesundheitsamt)"
* #1.03.3.55. "Landkreis Lüneburg (Gesundheitsamt)"
* #1.03.3.56. "Landkreis Osterholz (Gesundheitsamt)"
* #1.03.3.57. "Landkreis Rotenburg (Gesundheitsamt)"
* #1.03.3.58. "Landkreis Heidekreis (Fachbereich Gesundheit)"
* #1.03.3.59. "Landkreis Stade (Gesundheitsamt)"
* #1.03.3.60. "Landkreis Uelzen (Gesundheitsamt)"
* #1.03.3.61.02. "Landkreis Verden (Fachdienst Gesundheit und Umweltmedizin)"
* #1.03.4.01. "Stadt Delmenhorst (Städt. Gesundheitsamt)"
* #1.03.4.02. "Stadt Emden (Fachdienst 553 - Gesundheit)"
* #1.03.4.03. "Stadt Oldenburg (Gesundheitsamt)"
* #1.03.4.05. "Stadt Wilhelmshaven (Gesundheitsamt)"
* #1.03.4.51. "Landkreis Ammerland (Gesundheitsamt)"
* #1.03.4.52. "Landkreis Aurich (Amt für Gesundheitswesen)"
* #1.03.4.53. "Landkreis Cloppenburg (Gesundheitsamt)"
* #1.03.4.54. "Landkreis Emsland (Gesundheitsamt)"
* #1.03.4.55. "Landkreis Friesland (Gesundheitsamt)"
* #1.03.4.56. "Landkreis Grafschaft Bentheim (Gesundheitsamt)"
* #1.03.4.57. "Landkreis Leer (Gesundheitsamt)"
* #1.03.4.58. "Landkreis Oldenburg (Gesundheitsamt)"
* #1.03.4.59. "Landkreis Osnabrück (Fachdienst Gesundheit)"
* #1.03.4.60. "Landkreis Vechta (Gesundheitsamt)"
* #1.03.4.61. "Landkreis Wesermarsch (Fachdienst Gesundheit)"
* #1.03.4.62. "Landkreis Wittmund (Gesundheitsamt)"
* #1.04. "GA Bremen, Abteilung 3"
* #1.04.0.11. "Stadt Bremen (Gesundheitsamt)"
* #1.04.0.12. "Stadt Bremerhaven (Magistrat/Gesundheitsamt)"
* #1.05. "Landeszentrum Gesundheit NRW (Infektiologie und Hygiene)"
* #1.05.1.11. "Stadt Düsseldorf (Gesundheitsamt)"
* #1.05.1.12. "Stadt Duisburg (Gesundheitsamt)"
* #1.05.1.13. "Stadt Essen (Gesundheitsamt)"
* #1.05.1.14. "Stadt Krefeld (Fachbereich 53 Gesundheit)"
* #1.05.1.16. "Stadt Mönchengladbach (Fachbereich 53 Gesundheitsamt)"
* #1.05.1.17. "Stadt Mülheim (Gesundheitsamt)"
* #1.05.1.19. "Stadt Oberhausen (städtischer Bereich Gesundheitswesen)"
* #1.05.1.20. "Stadt Remscheid (Gesundheitswesen)"
* #1.05.1.22. "Stadt Solingen (Stadtdienst Gesundheit)"
* #1.05.1.24. "Stadt Wuppertal (Gesundheitsamt)"
* #1.05.1.54. "Landkreis Kleve (Kreisgesundheitsamt)"
* #1.05.1.58. "Landkreis Mettmann (Gesundheitsamt)"
* #1.05.1.62. "Landkreis Rheinkreis Neuss (Gesundheitsamt)"
* #1.05.1.66. "Landkreis Viersen (Gesundheitsamt)"
* #1.05.1.70. "Landkreis Wesel (Fachbereich Gesundheitswesen)"
* #1.05.3.14. "Stadt Bonn (Amt 53 Gesundheitsamt)"
* #1.05.3.15. "Stadt Köln (Gesundheitsamt)"
* #1.05.3.16. "Stadt Leverkusen (Fachbereich 53 Medizinischer Dienst(MediLev))"
* #1.05.3.34. "StädteRegion Aachen (Gesundheitsamt (A53))"
* #1.05.3.58. "Kreis Düren (Gesundheitsamt)"
* #1.05.3.62. "Kreisverwaltung Rhein-Erft-Kreis (Gesundheitsamt)"
* #1.05.3.66. "Kreis Euskirchen (Abteilung Gesundheit)"
* #1.05.3.70. "Kreis Heinsberg (Gesundheitsamt)"
* #1.05.3.74. "Oberbergischer Kreis (Gesundheitsamt)"
* #1.05.3.78. "Rheinisch-Bergischer Kreis (Der Landrat)"
* #1.05.3.82. "Rhein-Sieg-Kreis (Der Landrat/Gesundheitsamt)"
* #1.05.5.12. "Stadt Bottrop (Gesundheitsamt)"
* #1.05.5.13. "Stadt Gelsenkirchen (Referat Gesundheit)"
* #1.05.5.15. "Stadt Münster (Amt für Gesundheit, Veterinär- und Lebensmittelangelegenheiten)"
* #1.05.5.54. "Kreis Borken (Fachbereich Gesundheit)"
* #1.05.5.58. "Kreis Coesfeld (Gesundheitsamt)"
* #1.05.5.62. "Kreis Recklinghausen (Fachdienst 53 Gesundheit)"
* #1.05.5.66. "Kreis Steinfurt (Gesundheitsamt)"
* #1.05.5.70. "Kreis-Warendorf (Gesundheitsamt)"
* #1.05.7.11. "Stadt Bielefeld (Gesundheits-, Veterinär- u. Lebensmittelüberwachungsamt)"
* #1.05.7.54. "Kreis Gütersloh (Abteilung Gesundheit)"
* #1.05.7.58. "Kreis Herford (53.3 Abt. Gesundheit)"
* #1.05.7.62. "Kreisverwaltung Höxter (Gesundheits- und Veterinärwesen)"
* #1.05.7.66. "Gesundheitsamt Kreis Lippe (FG 530 Gesundheit)"
* #1.05.7.70. "Kreis Minden-Lübbecke (Gesundheitsamt)"
* #1.05.7.74. "Kreis Paderborn (Gesundheitsamt)"
* #1.05.9.11. "Stadt Bochum (Gesundheitsamt)"
* #1.05.9.13. "Stadt Dortmund (Gesundheitsamt)"
* #1.05.9.14. "Stadt Hagen (Gesundheitsamt Rathaus II)"
* #1.05.9.15. "Stadt Hamm (Gesundheitsamt)"
* #1.05.9.16. "Stadt Herne (Fachbereich Gesundheit)"
* #1.05.9.54. "Landkreis Ennepe-Ruhr-Kreis (Fachbereich Soziales und Gesundheit)"
* #1.05.9.58. "Hochsauerlandkreis (Gesundheitsamt Fachdienst 37)"
* #1.05.9.62. "Märkischer Kreis (Gesundheitsamt)"
* #1.05.9.66. "Kreis Olpe (Fachdienst Gesundheit)"
* #1.05.9.70. "Kreis Siegen-Wittgenstein (Gesundheit und Verbraucherschutz)"
* #1.05.9.74. "Kreis Soest (Ordnung, Gesundheits- und Verbraucherschutz)"
* #1.05.9.78. "Kreis Unna (Gesundheit und Verbraucherschutz)"
* #1.06. "Hessisches Landesprüfungs- und Untersuchungsamt im Gesundheitswesen"
* #1.06.4.12. "Stadt Frankfurt am Main (Gesundheitsamt)"
* #1.06.4.13. "Stadt Offenbach (Gesundheitsamt)"
* #1.06.4.14. "Landeshauptstadt Wiesbaden (Gesundheitsamt)"
* #1.06.4.31. "Kreisausschuss Kreis Bergstraße (Fachdienst Gesundheitswesen)"
* #1.06.4.32. "Landkreis Darmstadt-Dieburg (Gesundheitsamt)"
* #1.06.4.33. "Kreis Groß-Gerau (Der Kreisausschuß)"
* #1.06.4.34. "Kreisausschuss Hochtaunuskreis (Fachbereich Gesundheitsdienste)"
* #1.06.4.35. "Kreis Main-Kinzig (Gesundheitsamt Hygiene u. Umwelzmedizin)"
* #1.06.4.36. "Kreis Main-Taunus (Gesundheitsamt)"
* #1.06.4.37. "Kreisausschuss Odenwaldkreis (Gesundheitsamt)"
* #1.06.4.38. "Kreis Offenbach (FD Gefahrenabwehr- und Gesundheitszentrum)"
* #1.06.4.39. "Kreisausschuss Rheingau-Taunus (Gesundheitsamt)"
* #1.06.4.40. "Wetteraukreis (Fachdienstes Gesundheit und Gefahrenabwehr)"
* #1.06.5.31. "Landkreis Gießen (Gesundheit)"
* #1.06.5.32. "Kreisausschuß des Lahn-Dill-Kreises (Gesundheitsamt)"
* #1.06.5.33. "Kreisausschuss Limburg-Weilburg (Gesundheitsamt Dienststelle Limburg)"
* #1.06.5.33.01. "Kreisausschuss Limburg-Weilburg (Gesundheitsamt Dienststelle Weilburg)"
* #1.06.5.34. "Kreisausschuss Marburg-Biedenkopf (Fachbereich Gesundheitsamt)"
* #1.06.5.35. "Landkreis Vogelsbergkreis (Gesundheitsamt)"
* #1.06.6.11. "Region Kassel (Gesundheitsamt)"
* #1.06.6.31. "Kreisausschuss Fulda (Gesundheitsamt)"
* #1.06.6.32. "Kreisausschuss Hersfeld-Rotenburg (Fachdienst Gesundheit)"
* #1.06.6.34. "Kreisausschuss des Schwalm-Eder-Kreises (Fachbereich 53 - Gesundheit, Verbraucherschutz und Veterinärwesen)"
* #1.06.6.35. "Kreisausschuss des Landkreises Waldeck-Frankenberg (Fachdienst 5.1 Gesundheit)"
* #1.06.6.36. "Kreisausschuss Werra-Meißner (Fachbereich Gesundheit, Verbraucherschutz und Veterinärwesen)"
* #1.07. "LUA-Rheinland-Pfalz (Institut für Hygiene und Infektionsschutz)"
* #1.07.0.52. "Kreisverwaltung Mayen-Koblenz (Gesundheitsamt Nebenstelle)"
* #1.07.0.53. "Kreisverwaltung Rhein-Lahn Kreis (Abt. 7 Gesundheitswesen)"
* #1.07.0.54. "Kreisverwaltung Bad Kreuznach (Amt 7: Gesundheitsamt)"
* #1.07.0.56. "Kreisverwaltung Ahrweiler (Abt. 2.6 - Gesundheitsamt)"
* #1.07.0.58. "Kreisverwaltung  Eifelkreis Bitburg-Prüm (Amt 14 Gesundheitswesen)"
* #1.07.0.59. "Kreisverwaltung Cochem-Zell (Abt. Gesundheitsamt)"
* #1.07.0.60. "Kreisverwaltung Vulkaneifel (Gesundheitsamt)"
* #1.07.0.63. "Kreisverwaltung Germersheim (FB 43 Gesundheit, Verbraucherschutz)"
* #1.07.0.64. "Kreisverwaltung Birkenfeld (Gesundheitsamt - Abt. 5)"
* #1.07.0.65. "Kreisverwaltung Kaiserslautern (Gesundheitsamt)"
* #1.07.0.66. "Kreisverwaltung Donnersbergkreis (Abt. 7 Umweltschutz, Gesundheit)"
* #1.07.0.67. "Kreisverwaltung Mayen-Koblenz (Abt. Gesundheitsamt)"
* #1.07.0.68. "Kreisverwaltung Kusel (Gesundheitsamt)"
* #1.07.0.69. "Landkreis Südliche Weinstraße / Landau (Amt für Gesundheit und Soziales)"
* #1.07.0.70. "Kreisverwaltung Rhein-Pfalz-Kreis (Gesundheitsamt)"
* #1.07.0.71. "Kreisverwaltung Mainz-Bingen (Amt für Veterinär- und Gesundheitswesen)"
* #1.07.0.72. "Kreisverwaltung Mayen-Koblenz (Gesundheitsamt Nebenstelle)"
* #1.07.0.73. "Kreisverwaltung Westerwaldkreises (Gesundheitsamt)"
* #1.07.0.74. "Kreisverwaltung Bad Dürkheim/Neustadt (Abteilung 7: Gesundheitsamt)"
* #1.07.0.75. "Kreisverwaltung Neuwied (Abt. 11 Gesundheitsamt)"
* #1.07.0.76. "Kreisverwaltung Südwestpfalz/Pirmasens (Abt. Gesundheitswesen)"
* #1.07.0.80. "Kreisverwaltung Rhein-Hunsrück-Kreis/Simmern (Fachbereich Gesundheitsamt)"
* #1.07.0.82. "Kreisverwaltung Trier-Saarburg (Abt. Gesundheitsamt)"
* #1.07.0.83. "Kreisverwaltung Bernkastel-Wittlich (FB33 Gesundheit)"
* #1.07.0.84. "Kreisverwaltung Alzey-Worms (Abt 7 - Referat Gesundheitsamt)"
* #1.07.1.32. "Kreisverwaltung Altenkirchen (Gesundheitsamt)"
* #1.08. "Regierungspräsidium Stuttgart (Referat 95 - Epidemiologie und Gesundheitsberichterstattung)"
* #1.08.1.11. "Landeshauptstadt Stuttgart (Gesundheitsamt)"
* #1.08.1.15. "Landratsamt Böblingen (Gesundheitsamt)"
* #1.08.1.16. "Landratsamt Esslingen (Gesundheitsamt)"
* #1.08.1.17. "Landratsamt Göppingen (Gesundheitsamt)"
* #1.08.1.18. "Landratsamt Ludwigsburg (Gesundheitsamt)"
* #1.08.1.19. "Landratsamt Rems-Murr-Kreis (Geschäftsbereich Gesundheit)"
* #1.08.1.21. "Stadt Heilbronn (Städtisches Gesundheitsamt)"
* #1.08.1.25. "Landratsamt Heilbronn (Gesundheitsamt)"
* #1.08.1.26. "Landratsamt Hohenlohekreis (Gesundheitsamt)"
* #1.08.1.27. "Landratsamt Schwäbisch Hall (Gesundheitsamt)"
* #1.08.1.28. "Landratsamt Main-Tauber-Kreis (Gesundheitsamt)"
* #1.08.1.35. "Landratsamt Heidenheim (Fachbereich Gesundheit)"
* #1.08.1.36. "Landratsamt Ostalbkreis (Gesundheitsamt)"
* #1.08.2.15. "Landratsamt Karlsruhe (Gesundheitsamt)"
* #1.08.2.16. "Landratsamt Rastatt (Gesundheitsamt)"
* #1.08.2.22. "Stadt Mannheim (Fachbereich Gesundheit)"
* #1.08.2.25. "Landratsamt Neckar-Odenwald-Kreis (Gesundheitsamt)"
* #1.08.2.26. "Landratsamt Rhein-Neckar-Kreis (Gesundheitsamt)"
* #1.08.2.35. "Landratsamt Calw (Abt. 42 Gesundheit und Versorgung)"
* #1.08.2.36. "Landratsamt Enzkreis (Gesundheitsamt)"
* #1.08.2.37. "Landratsamt Freudenstadt (Gesundheitsamt)"
* #1.08.3.15. "Landratsamt Breisgau-Hochschwarzwald (Gesundheitsamt)"
* #1.08.3.16. "Landratsamt Emmendingen (Gesundheitsamt)"
* #1.08.3.17. "Landratsamt Ortenaukreis (Gesundheitsamt)"
* #1.08.3.25. "Landratsamt Rottweil (Gesundheitsamt)"
* #1.08.3.26. "Landratsamt Schwarzwald-Baar-Kreis (Gesundheitsamt)"
* #1.08.3.27. "Landratsamt Tuttlingen (Gesundheitsamt (Amt 42))"
* #1.08.3.35. "Landratsamt Konstanz (Amt für Gesundheit und Versorgung)"
* #1.08.3.36. "Landratsamt Lörrach (Fachbereich Gesundheit)"
* #1.08.3.37. "Landratsamt Waldshut (Gesundheitsamt)"
* #1.08.4.15. "Landratsamt Reutlingen (Kreisgesundheitsamt)"
* #1.08.4.16. "Landratsamt Tübingen (Abteilung 33 Gesundheit)"
* #1.08.4.17. "Landratsamt Zollernalbkreis (Gesundheitsamt)"
* #1.08.4.25. "Landratsamt Alb-Donau-Kreis (Fachdienst Gesundheit)"
* #1.08.4.26. "Landratsamt Biberach (Kreisgesundheitsamt)"
* #1.08.4.35. "Landratsamt Bodenseekreis (Gesundheitsamt)"
* #1.08.4.36. "Landratsamt Ravensburg (Gesundheitsamt)"
* #1.08.4.37. "Landratsamt Sigmaringen (Fachbereich Gesundheit)"
* #1.09. "Bayerisches Landesamt für Gesundheit und Lebensmittelsicherheit"
* #1.09.1.61. "Stadt Ingolstadt (Gesundheitsamt)"
* #1.09.1.62. "Landeshauptstadt München (Referat für Gesundheit und Umwelt)"
* #1.09.1.71. "Landratsamt Altötting (Gesundheits- und Veterinärwesen)"
* #1.09.1.72. "Landratsamt Berchtesgadener Land (Gesundheitsamt)"
* #1.09.1.73.02. "Landkreis Bad Tölz - Wolfratshausen (Landratsamt)"
* #1.09.1.74. "Landratsamt Dachau (Gesundheitsamt)"
* #1.09.1.75. "Landratsamt Ebersberg (Gesundheitsamt)"
* #1.09.1.76. "Landratsamt Eichstätt (Gesundheitswesen)"
* #1.09.1.77. "Landratsamt Erding (Abteilung 5 - Gesundheitsamt)"
* #1.09.1.78. "Landratsamt Freising (Gesundheitsamt Freising)"
* #1.09.1.79. "Landratsamt Fürstenfeldbruck (Gesundheitsamt)"
* #1.09.1.80. "Landratsamt Garmisch-Partenkirchen (Gesundheitsamt Garmisch-Partenkirchen)"
* #1.09.1.81. "Landkreis Landsberg a.Lech (Landratsamt Landsberg am Lech - Außenstelle 2)"
* #1.09.1.82. "Landratsamt Miesbach (Fachbereich 43 Gesundheitsamt)"
* #1.09.1.83. "Landratsamt Mühldorf am Inn (Gesundheitsamt)"
* #1.09.1.84. "Landratsamt München (Abteilung 4 - Öffentliches Gesundheits- und Veterinärwesen)"
* #1.09.1.85.01. "Landratsamt Neuburg-Schrobenhausen (Gesundheitsamt)"
* #1.09.1.86. "Landratsamt Pfaffenhofen (Gesundheitsamt)"
* #1.09.1.87. "Landratsamt Rosenheim (Staatliches Gesundheitsamt)"
* #1.09.1.88. "Landratsamt Starnberg (Fachbereich 32 Gesundheitswesen)"
* #1.09.1.89. "Landratsamt Traunstein (Gesundheitsamt)"
* #1.09.1.90. "Landratsamt Weilheim-Schongau (Abteilung 6 - Gesundheitsamt)"
* #1.09.2.71. "Landratsamt Deggendorf (Gesundheitswesen)"
* #1.09.2.72. "Landratsamt Freyung-Grafenau (Gesundheitsamt)"
* #1.09.2.73. "Landratsamt Kelheim (Gesundheitsabteilung)"
* #1.09.2.74. "Landratsamt Landshut (Gesundheitsamt)"
* #1.09.2.75. "Landratsamt Passau (Gesundheitsamt)"
* #1.09.2.76. "Landratsamt Regen (Gesundheitsamt)"
* #1.09.2.77. "Landratsamt Rottal-Inn (Abt. 4 Gesundheits-und Veterinärwesen)"
* #1.09.2.78. "Landratsamt Straubing-Bogen (Abteilung Gesundheitswesen)"
* #1.09.2.79. "Landratsamt Dingolfing-Landau (Gesundheitsamt)"
* #1.09.3.61.01. "Landratsamt Amberg-Sulzbach (Gesundheitsamt)"
* #1.09.3.72. "Landratsamt Cham (Gesundheitswesen)"
* #1.09.3.73. "Landratsamt Neumarkt i.d.Oberpfalz (Gesundheitsamt)"
* #1.09.3.74. "Landratsamt Neustadt a. d. Waldnaab/ Weiden (Abteilung Gesundheitswesen)"
* #1.09.3.75. "Landratsamt Regensburg (Gesundheitsamt)"
* #1.09.3.76.01. "Landratsamt Schwandorf (Gesundheitsamt)"
* #1.09.3.77. "Landratsamt Tirschenreuth (Gesundheitsamt)"
* #1.09.4.71. "Landratsamt Bamberg (Fachbereich 23 Gesundheitswesen)"
* #1.09.4.72. "Landratsamt Bayreuth (Abteilung Gesundheitswesen)"
* #1.09.4.73. "Landratsamt Coburg (FB 32 Gesundheit)"
* #1.09.4.74. "Landratsamt Forchheim (Gesundheitsamt)"
* #1.09.4.75. "Landratsamt Hof (Abt. 7 Gesundheitswesen)"
* #1.09.4.76. "Landratsamt Kronach (Sachgebiet 36 - Gesundheitsamt)"
* #1.09.4.77. "Landratsamt Kulmbach (Gesundheitsamt)"
* #1.09.4.78. "Landratsamt Lichtenfels (Abt. Gesundheitswesen)"
* #1.09.4.79. "Landratsamt Wunsiedel i.Fichtelgeb. (Fachbereich Gesundheitswesen)"
* #1.09.5.61. "Landratsamt Ansbach (Gesundheitsamt)"
* #1.09.5.64. "Stadt Nürnberg (Gesundheitsamt)"
* #1.09.5.72.01. "Landratsamt Erlangen-Höchstadt (Gesundheitsamt)"
* #1.09.5.73. "Landratsamt Fürth (Gesundheitsamt)"
* #1.09.5.74. "Landratsamt Nürnberger Land (Gesundheitsamt)"
* #1.09.5.75. "Landratsamt Neustadt a.d.Aisch-Bad Windsheim (Gesundheitsamt)"
* #1.09.5.76. "Landratsamt Roth (Gesundheitsamt)"
* #1.09.5.77. "Landratsamt Weißenburg-Gunzenhausen (Gesundheitsamt)"
* #1.09.6.71. "Landratsamt Aschaffenburg (Abteilung 5 - Gesundheitsamt)"
* #1.09.6.72. "Landkreis Bad Kissingen (Staatliches Gesundheitsamt)"
* #1.09.6.73. "Landkreis Rhön-Grabfeld (3.4 Gesundheitswesen)"
* #1.09.6.74. "Landratsamt Hassberge (Fachabteilung II/A)"
* #1.09.6.75. "Landratsamt Kitzingen (Gesundheitsamt)"
* #1.09.6.76. "Landratsamt Miltenberg (Gesundheitsamt)"
* #1.09.6.77. "Landratsamt Main-Spessart (Staatliches Gesundheitsamt)"
* #1.09.6.78. "Landratsamt Schweinfurt (Gesundheitsamt)"
* #1.09.6.79. "Landratsamt Würzburg (Fachbereich 34)"
* #1.09.7.61. "Stadt Augsburg (Gesundheitsamt)"
* #1.09.7.64. "Stadt Memmingen (Gesundheitsamt)"
* #1.09.7.71. "Landratsamt Aichach-Friedberg (Gesundheitsamt)"
* #1.09.7.72. "Landratsamt Augsburg (Gesundheitsamt)"
* #1.09.7.73. "Landratsamt Dillingen (Fachbereich Gesundheit)"
* #1.09.7.74. "Landratsamt Günzburg (Gesundheitsamt)"
* #1.09.7.75. "Landratsamt Neu-Ulm (Öffentlicher Gesundheitsdienst)"
* #1.09.7.76. "Landratsamt Lindau (Fachbereich Gesundheit)"
* #1.09.7.77. "Landkreis Ostallgäu (Gesundheitsamt)"
* #1.09.7.78. "Landratsamt Unterallgäu (Gesundheitsamt)"
* #1.09.7.79.01. "Landratsamt Donau-Ries (Gesundheitsamt)"
* #1.09.7.80. "Landratsamt Oberallgäu (Gesundheitsamt)"
* #1.10. "Ministerium für Soziales, (Abteilung E Gesundheit)"
* #1.10.0.41. "Regionalverbandes Saarbrücken (Gesundheitsamt)"
* #1.10.0.42. "Landkreis Merzig-Wadern (Gesundheitsamt)"
* #1.10.0.43. "Landkreis Neunkirchen (Kreisgesundheitsamt)"
* #1.10.0.44. "Landkreis Saarlouis (Gesundheitsamt)"
* #1.10.0.45. "Saarpfalz-Kreis (Gesundheitsamt)"
* #1.10.0.46. "Landkreis St. Wendel (Gesundheitsamt)"
* #1.11. "Landesamt Berlin (Gesundheit und Soziales)"
* #1.11.0.01.01. "Bezirksamt Mitte von Berlin , Abt. Gesundheit (Gesundheitsamt)"
* #1.11.0.02.01. "Bezirksamt Friedrichshain-Kreuzberg von Berlin (Gesundheitsamt)"
* #1.11.0.03.01. "Bezirksamt Pankow von Berlin (Abt. Gesundheit und Soziales)"
* #1.11.0.04.01. "Bezirksamt Charlottenburg-Wilmersdorf von Berlin (Gesundheitsamt)"
* #1.11.0.05.01. "Bezirksamt Spandau von Berlin (Gesundheitsamt)"
* #1.11.0.06.01. "Bezirksamt Steglitz-Zehlendorf von Berlin (Gesundheitsamt)"
* #1.11.0.07.01. "Bezirksamt Tempelhof-Schöneberg von Berlin (Gesundheitsamt)"
* #1.11.0.08.01. "Bezirksamt Neukölln von Berlin (Gesundheitsamt)"
* #1.11.0.09.01. "Bezirksamt Treptow-Köpenick von Berlin (Gesundheitsamt)"
* #1.11.0.10.01. "Bezirksamt Marzahn-Hellersdorf von Berlin (Abteilung Gesundheit und Soziales)"
* #1.11.0.11.01. "Bezirksamt Lichtenberg von Berlin (Abt. Umwelt und Gesundheit)"
* #1.11.0.11.09. "Bezirksamt Lichtenberg von Berlin (Gesundheitsamt)"
* #1.11.0.12.01. "Bezirksamt Reinickendorf von Berlin (Gesundheitsamt)"
* #1.12. "Landesamt für Umwelt, Gesundheit und Verbraucherschutz (Abteilung Gesundheit)"
* #1.12.0.51. "Stadtverwaltung Brandenburg (Gesundheits-, Veterinär- und Lebensmittelüberwachungsamt)"
* #1.12.0.52. "Stadt Cottbus/S (Fachbereich 53 Gesundheit)"
* #1.12.0.53. "Stadt Frankfurt/Oder (Gesundheitsamt)"
* #1.12.0.54. "Landeshauptstadt Potsdam (Gesundheitsamt)"
* #1.12.0.60. "Landkreis Barnim (Dienstleistungs- und Verwaltungszentrum/ Paul Wunderlich Haus)"
* #1.12.0.61. "Landkreis Dahme- Spreewald (Gesundheitsamt)"
* #1.12.0.62. "Landkreis Elbe-Elster (Gesundheitsamt)"
* #1.12.0.63. "Landkreis Havelland (Gesundheitsamt)"
* #1.12.0.64. "Landkreis Märkisch- Oderland (Gesundheitsamt FB II)"
* #1.12.0.65. "Landkreis Oberhavel (Gesundheitsamt)"
* #1.12.0.66. "Landkreis Oberspreewald- Lausitz (Gesundheitsamt)"
* #1.12.0.67. "Landkreis Oder- Spree (Gesundheitsamt)"
* #1.12.0.68. "Kreisverwaltung Ostprignitz- Ruppin (Gesundheitsamt)"
* #1.12.0.69. "Landkreis Potsdam-Mittelmark (Fachdienst Gesundheit)"
* #1.12.0.70. "Landkreis Prignitz (Gesundheitsamt)"
* #1.12.0.71. "Landkreis Spree-Neiße (Fachbereich Gesundheit)"
* #1.12.0.72. "Landkreis Teltow-Fläming (Dezernat II Gesundheitsamt)"
* #1.12.0.73. "Landkreis Uckermark (Gesundheits- und Veterinäramt)"
* #1.13. "Landesamt für Gesundheit und Soziales M-V (Abteilung Gesundheit)"
* #1.13.0.03. "Stadt Rostock (Gesundheitsamt)"
* #1.13.0.04. "Landeshauptstadt Schwerin (Fachdienst Gesundheit)"
* #1.13.0.71. "Landkreis Mecklenburgische Seenplatte (Gesundheitsamt)"
* #1.13.0.72. "Landkreis Rostock (Gesundheitsamt Güstrow)"
* #1.13.0.73. "Landkreis Vorpommern-Rügen (Fachdienst Gesundheit)"
* #1.13.0.74. "Landkreis Nordwestmecklenburg (Fachdienst Öffentlicher Gesundheitsdienst)"
* #1.13.0.75. "Landkreis Vorpommern–Greifswald (Gesundheitsamt)"
* #1.13.0.76. "Landkreis Ludwigslust-Parchim (Gesundheitsamt)"
* #1.14. "Landesuntersuchungsanstalt für das Gesundheits- und Veterinärwesen Sachsen"
* #1.14.5.11. "Stadt Chemnitz (Gesundheitsamt)"
* #1.14.5.21.02. "Landkreis Erzgebirgskreis (Gesundheitsamt)"
* #1.14.5.22.01. "Landkreis Mittelsachsen (Gesundheitsamt)"
* #1.14.5.23.02. "Landkreis Vogtlandkreis (Gesundheitsamt)"
* #1.14.5.24.01. "Landkreis Zwickau (Gesundheitsamt)"
* #1.14.6.12. "Landeshauptstadt Dresden (Gesundheitsamt)"
* #1.14.6.25.03. "Landratsamt Bautzen (Gesundheitsamt)"
* #1.14.6.26.01. "Landkreis Görlitz (Gesundheitsamt)"
* #1.14.6.27.01. "Landkreis Meißen (Gesundheitsamt)"
* #1.14.6.28.01. "Landkreis Sächsische Schweiz - Osterzgebirge (Abteilung Gesundheit)"
* #1.14.7.13. "Stadt Leipzig (Gesundheitsamt)"
* #1.14.7.29.01. "Landratsamt Leipzig (Gesundheitsamt (Hauptsitz))"
* #1.14.7.30.01. "Landratsamt Nordsachsen (Gesundheitsamt)"
* #1.15. "Landesamt für Verbraucherschutz (Sachsen-Anhalt)"
* #1.15.0.01. "Stadt Dessau-Roßlau (Gesundheitsamt/Veterinärwesen und Verbaucherschutz)"
* #1.15.0.02. "Stadt Halle (Saale) (Fachbereich Gesundheit)"
* #1.15.0.03. "Landeshauptstadt Magdeburg (Gesundheits- und Veterinäramt)"
* #1.15.0.81. "Altmarkkreis Salzwedel (Gesundheitsamt)"
* #1.15.0.82.02. "Landkreis Anhalt- Bitterfeld (Gesundheitsamt - Köthen (Anhalt))"
* #1.15.0.83.01. "Landkreis Börde (Fachdienst Gesundheit)"
* #1.15.0.84.02. "Burgenlandkreis (Gesundheitsamt)"
* #1.15.0.85.03. "Landkreis Harz (Gesundheitsamt - Wernigerode)"
* #1.15.0.86. "Landkreis Jerichower Land (Gesundheitsamt)"
* #1.15.0.87.02. "Landkreis Mansfeld-Südharz (Gesundheitsamt)"
* #1.15.0.88.02. "Landkreis Saalekreis (Gesundheitsamt)"
* #1.15.0.89.01. "Salzlandkreis (34 Fachdienst Gesundheit)"
* #1.15.0.90. "Landkreis Stendal (Gesundheitsamt)"
* #1.15.0.91. "Landkreis Wittenberg (Fachdienst Gesundheit)"
* #1.16. "Thüringer Landesamt (Lebensmittelsicherheit und Verbraucherschutz (TLLV))"
* #1.16.0.51. "Landeshauptstadt Erfurt (Amt für Soziales und Gesundheit)"
* #1.16.0.52. "Stadt Gera (Fachdienst Gesundheit)"
* #1.16.0.53. "Stadtverwaltung Jena (Fachdienst Gesundheit)"
* #1.16.0.54. "Stadtverwaltung Suhl (Gesundheitsamt)"
* #1.16.0.55. "Stadtverwaltung Weimar (Gesundheitsamt)"
* #1.16.0.61. "Landkreis Eichsfeld (Gesundheitsamt)"
* #1.16.0.62. "Landratsamt Nordhausen (Gesundheitsamt)"
* #1.16.0.63. "Landratsamt Wartburgkreis (Gesundheitsamt)"
* #1.16.0.64.01. "Landratsamt Unstrut-Hainich-Kreis (FD Gesundheit)"
* #1.16.0.65.01. "Landratsamt Kyffhäuserkreis (Gesundheitsamt)"
* #1.16.0.66. "Landratsamt Schmalkalden-Meiningen (Fachbereich Gesundheit)"
* #1.16.0.67. "Landratsamt Gotha (Gesundheitsamt)"
* #1.16.0.68. "Landratsamt Sömmerda (Gesundheitsamt)"
* #1.16.0.69. "Landratsamt Hildburghausen (Gesundheitsamt)"
* #1.16.0.70.02. "Landratsamt Ilm-Kreis (Gesundheitsamt)"
* #1.16.0.71. "Landratsamt Weimarer Land (Gesundheitsamt)"
* #1.16.0.72. "Landratsamt Sonneberg (Gesundheitsamt)"
* #1.16.0.73.02. "Landratsamt Saalfeld-Rudolstadt (Gesundheitsamt)"
* #1.16.0.74. "Landratsamt Saale-Holzland-Kreis (Gesundheitsamt)"
* #1.16.0.75.03. "Landratsamt Saale-Orla-Kreis (Fachdienst Amtsärztlicher Dienst)"
* #1.16.0.76. "Landratsamt Greiz (Gesundheitsamt)"
* #1.16.0.77. "Landratsamt Altenburger Land (Fachdienst Gesundheit)"
* #1.17. "Kommando Sanitätsdienst der Bundeswehr"
* #1.17.0.01. "ÜbwSt ÖRA Nord (für HB, HH, MV, NI, SH)"
* #1.17.0.02. "ÜbwSt ÖRA Ost (für BB, BE, SN, ST, TH)"
* #1.17.0.03. "ÜbwSt ÖRA Süd (für BW, BY)"
* #1.17.0.04. "ÜbwSt ÖRA West (für HE, NW, RP, SL)"


ValueSet: ResourceResponsibility
Id: ResourceResponsibility
Title: "ResourceResponsibility (Werteliste)"
Description: "Werteliste mit Konzepten, die die Verantwortlichkeit für Ressourcen auszeichnen."
* insert MetadataTerminology
* ^version = "1.0.0"
* ^date = "2024-03-19"
* include codes from system ResourceResponsibility

