@startuml
skinparam linetype ortho

title AffectedPersonBundle - Class Diagram

class AffectedPerson{
}

class EmigaUserPractitioner {
}

class EmigaOrganization {
}

class AffectedPersonBundle {
}

AffectedPerson --> AffectedPersonRelatedPerson

AffectedPerson --> EmigaOrganization

AffectedPerson --> EmigaUserPractitioner

AffectedPersonBundle ..> AffectedPerson
note on link: entry[x]

AffectedPersonBundle ..> EmigaOrganization
note on link: entry[x]

AffectedPersonBundle ..> EmigaUserPractitioner
note on link: entry[x]

AffectedPerson ..> AffectedPerson

@enduml