skinparam linetype ortho

title AffectedPerson (Profile of Patient) - Class Diagram

' Main Class
class AffectedPerson{
<b>+</b> name: HumannameDeBasis [0..*]
-- Meta --
<b>+</b> meta.extension:lastModifiedBy: Reference(EmigaUserPractitioner) [0..1]
<b>+</b> meta.profile:emigaprofile: canonical(StructureDefinition) [0..*]
<b>+</b> meta.security:responsibility: Coding [0..1]
<b>+</b> meta.security:visibility: Coding [0..1]
-- Identifiers --
<b>+</b> identifier:EmigaFileNumber: IdentifierEmigaFileNumber [1..1]
<b>+</b> identifier:EmigaID: IdentifierEmigaID [1..1]
<b>+</b> identifier:SurvNetFileNumber: IdentifierSurvNetFileNumber [0..1]
-- Personal Information --
<b>+</b> birthDate: date [0..1]
<b>+</b> deceasedBoolean: boolean [0..1]
<b>+</b> deceasedDateTime: dateTime [0..1]
<b>+</b> extension:citizenship: Complex [0..*]
<b>+</b> extension:landOfBirth: Coding [0..1]
<b>+</b> extension:processingStatus: Coding [0..1]
<b>+</b> gender: code [0..1]
<b>+</b> gender.extension:other-amtlich: Coding [0..1]
-- Communication --
<b>+</b> address.city: string [0..1]
<b>+</b> address.country: string [0..1]
<b>+</b> address.extension:addressUse: Coding [0..*]
<b>+</b> address.extension:facilityAssociation: Complex [0..*]
<b>+</b> address.extension:geolocation: Complex [0..1]
<b>+</b> address.extension:regionalKey: Complex [0..1]
<b>+</b> address.extension:Stadtteil: String [0..1]
<b>+</b> address.line.extension:Adresszusatz: String [0..1]
<b>+</b> address.line.extension:Hausnummer: String [0..1]
<b>+</b> address.line.extension:Postfach: String [0..1]
<b>+</b> address.line.extension:Strasse: String [0..1]
<b>+</b> address.postalCode: string [0..1]
<b>+</b> address.state: string [0..1]
<b>+</b> telecom:Email: ContactPoint [0..*]
<b>+</b> telecom:Fax: ContactPoint [0..*]
<b>+</b> telecom:Phone: ContactPoint [0..*]
-- Links --
<b>+</b> link:relatedPersonLink: Reference(RelatedPerson) [0..*]
}