@startuml
skinparam linetype ortho

title AffectedPerson (Profile of Patient) - Class Diagram

' Main Class
class AffectedPerson{
<b>+</b> name: HumannameDeBasis [0..*]
-- Meta --
<b>+</b> meta.extension:lastModifiedBy.value[x]: Reference(Practitioner) [1..1]
<b>+</b> meta.profile:emigaprofile: canonical(StructureDefinition) [0..*]
<b>+</b> meta.security:responsibility: Coding [0..1]
<b>+</b> meta.security:visibility: Coding [0..1]
-- Identifiers --
<b>+</b> identifier:EmigaFileNumber: IdentifierEmigaFileNumber [1..1]
<b>+</b> identifier:EmigaID: IdentifierEmigaID [1..1]
<b>+</b> identifier:SurvNetFileNumber: IdentifierSurvNetFileNumber [0..1]
-- Personal Information --
<b>+</b> birthDate: date [0..1]
<b>+</b> deceasedBoolean: boolean [0..1]
<b>+</b> deceasedDateTime: dateTime [0..1]
<b>+</b> extension:citizenship: Extension(Complex) [0..*]
<b>+</b> extension:landOfBirth: Extension(Coding) [0..1]
<b>+</b> extension:processingStatus: Extension(Coding) [0..1]
<b>+</b> gender: code [0..1]
<b>+</b> gender.extension:other-amtlich: Extension(Coding) [0..1]
-- Communication --
<b>+</b> address.city: string [0..1]
<b>+</b> address.country: string [0..1]
<b>+</b> address.extension:addressUse: Extension(Coding) [0..*]
<b>+</b> address.extension:facilityAssociation: Extension(Complex) [0..*]
<b>+</b> address.extension:geolocation: Extension(Complex) [0..1]
<b>+</b> address.extension:regionalKey: Extension(Complex) [0..1]
<b>+</b> address.extension:Stadtteil: Extension(string) [0..1]
<b>+</b> address.line.extension:Adresszusatz: Extension(string) [0..1]
<b>+</b> address.line.extension:Hausnummer: Extension(string) [0..1]
<b>+</b> address.line.extension:Postfach: Extension(string) [0..1]
<b>+</b> address.line.extension:Strasse: Extension(string) [0..1]
<b>+</b> address.postalCode: string [0..1]
<b>+</b> address.state: string [0..1]
<b>+</b> telecom:Email: ContactPoint [0..*]
<b>+</b> telecom:Fax: ContactPoint [0..*]
<b>+</b> telecom:Phone: ContactPoint [0..*]
-- Links --
<b>+</b> link:patientLink: BackboneElement [0..*]
<b>+</b> link:relatedPersonLink: BackboneElement [0..*]
}


@enduml