@startuml
skinparam linetype ortho

title AnnotationCommunicationBundle - Class Diagram

class AnnotationCommunicationBundle{
}
class AnnotationCommunication{
}
class Resource {
}
class AttachmentDocumentReference {
}
class EmigaUserPractitioner {
}

AnnotationCommunication --> EmigaUserPractitioner
note on link: sender
AnnotationCommunication --> AttachmentDocumentReference 
note on link: contentReference
AnnotationCommunication --> Resource
note on link: about

AnnotationCommunicationBundle ..> AnnotationCommunication
note on link: entry[x]
AnnotationCommunicationBundle ..> EmigaUserPractitioner
note on link: entry[x]
AnnotationCommunicationBundle ..> AttachmentDocumentReference
note on link: entry[x]
AnnotationCommunicationBundle ..> Resource
note on link: entry[x]
@enduml