@startuml
title AnnotationCommunication (Profile of Communication) - Class Diagram

' Main Class
class AnnotationCommunication{
' TODO andere IDs ignorieren wir?
<b>+</b> id: string [0..1]
-- Meta --
<b>+</b> meta.lastUpdated: instant [0..1] 
<b>+</b> meta.profile:emigaprofile: canonical(StructureDefinition) [0..*]
<b>+</b> meta.security:responsibility.display: string [0..1]
<b>+</b> meta.security:visibility.display: string [0..1]
<b>+</b> meta.source: uri [0..1] 
<b>+</b> meta.versionID: id [0..1] 
-- Identifiers --
<b>+</b> identifier:EmigaFileNumber.value: string [1..1] 
<b>+</b> identifier:EmigaID.value: string [1..1] 
<b>+</b> identifier:SurvNetFileNumber.value: string [0..1] 
-- Communication Content --
<b>+</b> about: Reference(Resource) [0..*] 
<b>+</b> category: CodeableConcept [0..*]
<b>+</b> extension:processingStatus: Extension(Coding) [1..1]
<b>+</b> extension:dateCreated: Extension(instant) [1..1]
<b>+</b> note: Annotation [0..*]
<b>+</b> payload.content[x]:contentReference: Reference(AttachmentDocumentReference) [0..1]
<b>+</b> payload.content[x]:contentString: string [0..1]
<b>+</b> sender: Reference(EmigaUserPractitioner) [1..1] 
<b>+</b> sent: dateTime [0..1]
<b>+</b> status: code [1..1]
<b>+</b> topic.text: string [1..1] 
}

@enduml