@startuml

title RelatedPerson - Class Diagram

class AffectedPerson{
}
class Relationship{
}
class AffectedPersonRelatedPerson {
}
class Patient {
}
class Relationship{
}

AffectedPerson --> AffectedPersonRelatedPerson: link

AffectedPersonRelatedPerson --> Patient: Bezugsperson
AffectedPersonRelatedPerson --> Relationship: Beziehung zur betroffenen Person

@enduml
